### PR TITLE
Only add ports with http and https protocol to ASPNETCORE_URLS

### PR DESCRIPTION
**Pull request by ikkentim**
Only add ports with http and https protocol to ASPNETCORE_URLS

Resolves https://github.com/dotnet/tye/issues/379

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/tye?pullRequest=916) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/tye?pullRequest=916) before we can accept your contribution.<br/><br/>:x: ikkentim [sign now](https://cla.dotnetfoundation.org/dotnet/tye?pullRequest=916)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/tye?pullRequest=916) it.</sub>

**Comment by ikkentim** [comment]
Can someone review this?

**Comment by ikkentim** [comment]
@philliphoff @pratiksanglikar I see you were added as code owner in this repo, could one of you possibly review this PR? Thanks!

**Comment by ikkentim** [comment]
@philliphoff Could you review this? I've been trying to get someone to review this for a few months now 😢

**Pull request closed without merging**
