### PR TITLE
Feature refactor core

### PR DESCRIPTION
**Pull request by sirh3e**
Refactored ApplicationFactory.cs

Applied language features on file ApplicationFactory.cs

### CODE REVIEW

**Comment by jkotalik** [comment]
There are some formatting issues that need to be resolved.

**Comment by sirh3e** [comment]
@jkotalik  How can i run formatting local to test it?

**Comment by jkotalik** [comment]
Two steps:
```powershell
. ./activate.ps1 # or .sh based on OS
dotnet format tye.sln
```

**Comment by sirh3e** [comment]
@jkotalik thx for the help 😃

**Pull request merged**
