### PR TITLE
add a custom reconnect dialog

### PR DESCRIPTION
**Pull request by anurse**
Fixes https://github.com/dotnet/tye/issues/14

I wanted to play with Tye and figured this was a quick fix to contribute ;).

I couldn't resist a little nerd jokery too, but I'm happy to edit it to be more "serious" if preferred:

The 'tye' dashboard, with a dark grey overlay and super-imposed text "Tye has exited. It is now safe to close this browser window."

### CODE REVIEW

**Comment by anurse** [comment]
I presume the failure is #303 ;)

**Comment by jkotalik** [comment]
I'm not a fan of the color scheme, it looks scary. I don't think we need to adjust the theme right now, @amarie401 thoughts?

I also think the text theme should match whatever the dashboard has.

What is the nerdy joke here?

**Comment by anurse** [comment]
Oof, you hit me right in the olds. (https://www.howtogeek.com/181295/yes-its-okay-to-shut-down-your-computer-with-the-power-button/)

I’m fine switching it to the standard styling, if that’s the preference :).

**Comment by anurse** [comment]
Alright, now that I'm done feeling super old, I swapped back to the previous color scheme. Same text though, so it still has that little Windows 95 inside joke for those who remember ;).

The 'tye' dashboard, with a light grey overlay and super-imposed text "Tye has exited. It is now safe to close this browser window."

**Pull request merged**
