### PR TITLE
Added support for additional routes on the Dashboard

### PR DESCRIPTION
**Pull request by ante-maric**
This PR covers issue #618 for supporting additional routes on the Dashboard in Bindings column. This makes it easier to navigate to endpoints that you access frequently like /swagger.

### CODE REVIEW

**Comment by davidfowl** [comment]
Some design feedback: Routes should be an array instead of a semicolon delimited String

**Comment by ante-maric** [comment]
> Some design feedback: Routes should be an array instead of a semicolon delimited String

Thanks for the feedback, I have applied the requested changes.

**Comment by digitaldias** [comment]
Any traction on this? Looking like it's closer now :)

**Comment by philliphoff** [comment]
@ante-maric Looks good to me, and rather handy! Thanks for the submission!  The only change I've made is to use blocks for the binding spans, as it starts to get hard to read with many routes.

@ravipal Since I've made changes myself, can you review as well?

**Review by ravipal — APPROVED** [review]

**Pull request merged**
