### PR TITLE
Make buttons pop a bit more

### PR DESCRIPTION
**Pull request by jkotalik**
Current because the buttons are the same color as the background, it's kind of hard to see. 

I made the gray for now. feel free to suggest other colors instead.
image

### CODE REVIEW

**Comment by amarie401** [comment]
I would suggest blue or red for call to action buttons

**Comment by rynowak** [comment]
Oh snap! Prepare to get front-ended 👍

**Comment by jkotalik** [comment]
image

**Comment by davidfowl** [comment]
My eyes

**Comment by amarie401** [comment]
@jkotalik let's hold off on this merge for a bit though, pending on what I can come up with :)

**Comment by jkotalik** [comment]
image

**Comment by jkotalik** [comment]
@amarie401 this is the best I have right now, if you are okay with that color, feel free to merge, otherwise you can make your first PR 😄

**Comment by jkotalik** [comment]
image

**Pull request merged**
