### PR TITLE
Revert changes to Dockerfile step

### PR DESCRIPTION
**Pull request by jkotalik**
Reverting a part of #236

### CODE REVIEW

**Comment by SimonCropp** [comment]
@jkotalik sorry. what did i break?

**Comment by davidfowl** [comment]
@SimonCropp moving where things get printed. Before VS after. These sorts of micro-optimizations don't really move the needle for a tool like this.

**Comment by SimonCropp** [comment]
@davidfowl ok. sorry about that. i was just reading the codebase, and submitting random things as i found them. i will stop doing the PR part now

**Comment by davidfowl** [comment]
I don't want to discourage contribution but I would refrain from micro-optimizations at this point. We have bigger performance things to work on at the moment. Like running msbuild 😢

**Comment by jkotalik** [comment]
Yeah, we encourage the contributions, this kind of optimization is very small when running and building takes over 5 seconds.

**Pull request merged**
