### PR TITLE
Update SDK

### LINKED ISSUE #660: Cannot Build tye after updating VS2019 16.8 preview3.0 / sdk 5.0.0-rc1 / VsCode (Lots of PackageReference are not loaded anymore)
### Describe the bug
As I was rebasing a PR and trying to fix a review comment on it, it seems that I can't use either VS2019 16.8 Preview 3.0 or VsCode (Insider) anymore
Lots of `PackageReference` are not visible in the dependency tree
Most of the errors are "Unknown class / namespace"
This picture is only a small part of all the errors
image

### To Reproduce
same on `master/main` branch
```pwsh
git clone https://github.com/dotnet/tye
checkout 
dotnet tool restore
./restore.cmd
./build.cmd
./startvs.cmd
```

Note that all of this works: 
* `build.cmd`
* `./eng/common/build.ps1 -build`
* `./eng/common/build.ps1 -test`

### Further technical details
- The platform : Windows
- dotnet --info:
```
C:\dev\github\tebeco\tye   multiple-target-frameworks ≣ 
[00:43]❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20211
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  2.1.809 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
 C:\dev\github\tebeco\tye   multiple-target-frameworks ≣ 
```

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Fixes #660 cc @tebeco

### CODE REVIEW

**Comment by tebeco** [comment]
will take a shoot at the branch in ~30-60min

**Comment by tebeco** [comment]
from the issue:

IIRC I might have seen a reference to System.Reactive (dotnet/réactive)

given the changes in recent prview about breaking changes regarding WinRT
Also Rx have dependencies towards WinRt (scheduler maybe ?)

You might want to recheck that the code of this repo using Rx still runs on RC1

especially after this comment from yesterday:

**Comment by tebeco** [comment]
I do confirm that fixes the bug from VS here too

**Comment by tebeco** [comment]
E2E seems also affected by `project.assets.json` somehow :D
image

**Comment by tebeco** [comment]
@JunTaoLuo 
I'm observing a strange behavior in `dotnet restore` and `dotnet build` on the generated `proj` file
image

**Comment by tebeco** [comment]
thx @JunTaoLuo for #674, rebasing this one seems ok now
This fixes the previous failure during E2E, especially the `dotnet restore` that now ... restore :D

I can't explain how most of the test used `docker` but not these :D
image

**Comment by JunTaoLuo** [comment]
Huh yea maybe those tests need to have updated conditions. I have Docker installed an running on my machines so I never noticed. FYI, I'm going to close this PR in favour of https://github.com/dotnet/tye/pull/668. That PR is our automation catching up with the SDK versions.

**Comment by tebeco** [comment]
docker detection seems flacky, I even added a `throw` in that `ConditionalFact` ... never throw even on rebuild, or clear all
had to re-run `./restore` I think eventually all ran
I think the same happened month ago in `dotnet/aspnetcore` regarding SignalR and redis tests

**Comment by tebeco** [comment]
#668 does not cover updating `netcoreapp3.1` to `net5.0` and also all the version in `global.json`
Is it something wanted at some point ?

**Pull request closed without merging**
