### PR TITLE
Update CombineStep.cs

### PR DESCRIPTION
**Pull request by sirh3e**
Replaced string == "http" by Equals("http")

See this blog post: https://docs.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings#default-ordinal-comparisons

### CODE REVIEW

**Comment by davidfowl** [comment]
This won't work because == also does a null check.

**Comment by sirh3e** [comment]
Fair point

**Comment by sirh3e** [comment]
But i must say that BindingBuilder.Protocol can be null makes no sense. You always use a protocol.

**Comment by sirh3e** [comment]
And the class BindingBuilder is not a builder at all it is more likey a container.

**Pull request closed without merging**
