### PR TITLE
Add status to services on dashboard

### PR DESCRIPTION
**Pull request by jkotalik**
@Finitereality

### CODE REVIEW

**Comment by jkotalik** [comment]
This PR needs some work, some of my testing showed this doesn't work in many scenarios.

**Comment by jkotalik** [comment]
Nvrm, this look okay. Locally though, you will rarely see the instance being down because the service restarts so quickly.

**Comment by jkotalik** [comment]
@davidfowl I know you have opinions on this.

**Comment by jkotalik** [comment]
@glennc @philliphoff thoughts on adding status icons to the dashboard?

**Comment by jongio** [comment]
We definitely need icons for colorblind accessibility perspective.  Some folks, like me, can't distinguish between green and red.

**Comment by jkotalik** [comment]
There are also checkmarks and 'x' for green and red.

**Comment by jkotalik** [comment]
Closing as this isn't making progress. Will reopen eventually.

**Pull request closed without merging**
