### PR TITLE
Fix NullRef in Tye run when not specifying and projects to debug.

### PR DESCRIPTION
**Pull request by jkotalik**
Should have tested doing `tye run` without debugging projects. Whoops.

### CODE REVIEW

**Comment by davidfowl** [comment]
This breaks normal `tye run`?

**Comment by jkotalik** [comment]
Yep.

**Comment by davidfowl** [comment]
Don't we have a test for that?

**Comment by jkotalik** [comment]
Added a new test. We have tests for `tye run` but it didn't call the right constructor.

**Pull request merged**
