### PR TITLE
Change version in getting_started for tye

### PR DESCRIPTION
**Pull request by jkotalik**
I made sure that tye run and tye deploy work, just in case. There a few bugs (https://github.com/dotnet/tye/issues/208, https://github.com/dotnet/tye/issues/205) that have already been fixed or have had docs that are updated that don't work against previous tye versions.

### CODE REVIEW

**Comment by davidfowl** [comment]
Oh wait, did we update the doc sytax as well? image vs dockerImage etc?

**Comment by jkotalik** [comment]
Yes, but I think we need to update the schema and a doc. I'll do that here.

**Comment by davidfowl** [comment]
@jkotalik The schema is already updated. It has both old and new though.

**Comment by jkotalik** [comment]
I don't think it's updated for the schema.

https://github.com/dotnet/tye/pull/213/files#diff-9762849daa5c598c4b9dc9e7130e0b92R175-R207.

image

**Comment by davidfowl** [comment]
Ah you're right

**Pull request merged**
