### PR TITLE
Fixed issue #620

### PR DESCRIPTION
**Pull request by ckadluba**
* Produce a useful error message if the path of a project file is incorrect in tye.yaml.
* Added a test.

### CODE REVIEW

**Comment by ckadluba** [comment]
Here is a small fix for issue #620 including a test. I humbly hope you find it useful.

**Comment by ckadluba** [comment]
Hmm .. I'm not sure why the Ubuntu build fails now. In the build logs there is this message about an ArgumentOutOfRangeException.

```
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'chunkLength')
   at System.Text.StringBuilder.ToString()
   at Microsoft.Tye.ProcessUtil.<>c__DisplayClass1_0.<RunAsync>b__2(Object _, EventArgs e) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 103
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.CompletionCallback(Object waitHandleContext, Boolean wasSignaled)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Aborted (core dumped)
```

I'll investigate this later.

**Comment by ckadluba** [comment]
It looks like my code change and test seem to work stable now but in the Ubuntu CI build there was an error in an unrelated test named MultiRepo_Works showing a network connection problem.

```
System.Net.Http.HttpRequestException : Connection refused\n---- System.Net.Sockets.SocketException : Connection refused
```

Could this be a transient infrastructure problem?

**Comment by glennc** [comment]
Re-running the tests had them all pass. @jkotalik have you noticed these being flaky in the past?

**Comment by ckadluba** [comment]
Hi guys! Any news on this?

**Comment by JunTaoLuo** [comment]
Thanks for the fix!

**Pull request merged**
