### PR TITLE
Remove PackageVersion tag with specific version number from tye.csproj

### PR DESCRIPTION
**Pull request by alexfdezsauco**
Remove PackageVersion tag with specific version number from tye.csproj

### CODE REVIEW

**Comment by jkotalik** [comment]
For my knowledge, why did you add this in the first place for your original PR? For local testing?

**Comment by alexfdezsauco** [comment]
Yes, for a local testing. Actually, for local development, while I waiting for the acceptance and the official prerelease version. But I forgot to ignore it in the PR. Sorry.

**Comment by jkotalik** [comment]
I see for testing out of repo.

**Comment by alexfdezsauco** [comment]
Can you also remove this microsoft.tye.0.2.0-dev-1 from the nuget feed? `d` is greater than `a` so, the next alpha updates will be not installed using `dotnet tool install -g Microsoft.Tye --version "0.2.0*"`.

**Comment by jkotalik** [comment]
@rynowak do you know how to do this for the azdo feed?

**Comment by rynowak** [comment]
this should be fixed now

**Pull request merged**
