### PR TITLE
Replace 'master' with 'main' in various files

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Review by jkotalik — APPROVED** [review]

**Comment by wtgodbe** [comment]
@jkotalik is the test failure in `ServiceWithoutReadinessShouldDefaultToReadyWhenHealthyTests` known?

**Comment by jkotalik** [comment]
No, feel free to file an issue.

Also, we've been seeing issues where the Windows build fails to show what test failed. Do you know more about why the test results wouldn't be uploaded?

**Comment by wtgodbe** [comment]
I'm not 100% sure, but it looks like the Windows job publishes test results to a different folder than the Unix jobs.

Win:

> ##[error]XUnit(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Tests failed: D:\workspace\_work\1\s\artifacts\log\Release\Microsoft.Tye.E2ETests_netcoreapp3.1_x64.log [netcoreapp3.1|x64]

OSX:

> ##[error]XUnit(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Tests failed: /Users/runner/work/1/s/artifacts/TestResults/Release/Microsoft.Tye.E2ETests_netcoreapp3.1_x64.html [netcoreapp3.1|x64]

**Comment by jkotalik** [comment]
Ah, can we switch that in this PR by chance?

**Comment by wtgodbe** [comment]
> Ah, can we switch that in this PR by chance?

I don't know offhand why it's different - looking at the artifacts, it's actually just the `Microsoft.Tye.E2ETests` that don't publish logs on Windows (at least, to the relevant artifacts dir - you can see this in the build artifacts). The other test libraries do publish test results/logs on Win. Would require some investigation to figure out why that particular test library is behaving differently. If you want I can help you look into it later today, but not as part of this PR.

**Pull request merged**
