### PR TITLE
Added tags to yaml definition to be used in CLI run filter

### LINKED ISSUE #493: Adding tags to yaml services definitions to be used in CLI run filter
### What should we add or change to make your life better?
Ability to tag services, 
``` yaml
name: myapplication
services:
- name: backend
  project: backend/backend.csproj
  tags:
  - tag1
  - tag2
- name: worker
  project: worker/worker.csproj
  tags:
  - tag3
```
and then use these tags in CLI to run only a subset of services:
``` powershell
tye run --tags=tag1,tag3
```
### Why is this important to you?
While I develop (on localhost) a system which has dozens of services, I usually don't need them all running on the same time and I would like to have the ability to run them by tags - grouped by modules or categories.

### PR DESCRIPTION
**Pull request by kkoziarski**
This resolves #493 and adds tags to yaml definition to be used in CLI run filter

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/tye?pullRequest=528) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/tye?pullRequest=528) before we can accept your contribution.<br/><br/>:x: kkoziarski [sign now](https://cla.dotnetfoundation.org/dotnet/tye?pullRequest=528)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/tye?pullRequest=528) it.</sub>

**Comment by jkotalik** [comment]
@kkoziarski did you sign the CLA?

**Comment by jkotalik** [comment]
Sweet, I'll look at this now 😄

**Comment by jkotalik** [comment]
@kkoziarski I went ahead and updated this PR with feedback. LGTM overall, had some minor nits and wanted to have tags supported for all scenarios.

**Comment by kkoziarski** [comment]
Great! It was fast :) Thanks.

**Pull request merged**
