### PR TITLE
Network configuration for Docker services

### PR DESCRIPTION
**Pull request by alexfdezsauco**
Some docker container configuration requires a network. In this pull request a network parameter is added to the ConfigService and used to create the docker container.

### CODE REVIEW

**Comment by davidfowl** [comment]
See https://github.com/dotnet/tye/pull/278.

**Comment by alexfdezsauco** [comment]
Looks like #278 include network creation. This pull request only include the usage of an existing network.

**Comment by alexfdezsauco** [comment]
@davidfowl is possible to use an existing network with #278?

**Comment by davidfowl** [comment]
Nope. If you have a scenario for that. Please file an issue so we can better understand the need

**Comment by alexfdezsauco** [comment]
Here is the feature: #282

BTW, I noticed that also mix changes in this pull request from other. In case of feature approval I will create a new one.

**Pull request closed without merging**
