### PR TITLE
Tye should validate that service names are valid DNS names 

### PR DESCRIPTION
**Pull request by kishanAnem**
#469

### CODE REVIEW

**Comment by kishanAnem** [comment]
I've opened clean PR #478. so closing this.

**Comment by kishanAnem** [comment]
Hi @jkotalik  @davidfowl  @rynowak I think this  PR is fine.

**Comment by jkotalik** [comment]
I'll take this PR from here (few small nitpicks I'd like to resolve but nothing major). Thanks again!

**Comment by jkotalik** [comment]
Closing for #480

**Pull request closed without merging**
