### PR TITLE
Add note about Dapr placement container requirement

### PR DESCRIPTION
**Pull request by dasiths**
The Tye documentation for Dapr integration (https://github.com/dotnet/tye/blob/master/docs/recipes/dapr.md) says all that's required is
```
extensions:
- name: dapr
```

but I need to also add this to the tye.yaml file to make it work
```
- name: placement
  image: daprio/dapr
  args: ./placement
  bindings:
    - port: 50005
```

I updated the documentation but please review and make sure it's correct.

### CODE REVIEW

**Comment by davidfowl** [comment]
That seems like we should just fix that bug

**Comment by dasiths** [comment]
> That seems like we should just fix that bug

I can raise it as a bug here but wasn't sure it was Tye or a Dapr issue. The current Dapr recipe sample in the Tye code base already has that yaml snippet included.

**Comment by dasiths** [comment]
I think I know how to fix it. Let me give it a crack.

**Comment by dasiths** [comment]
@davidfowl I created a PR and referenced this. Will close this now.

**Comment by jkotalik** [comment]
@dasiths I didn't have this issue when I was using the dapr sample in our repo locally. 

image

What tye version are you on? Is this issue resolved when you update to the latest release?

**Comment by jkotalik** [comment]
Nvrm, I didn't realize we updated our sample to include the placement service on a port now.

**Pull request closed without merging**
