### PR TITLE
Update ApplicationFactory.cs

### PR DESCRIPTION
**Pull request by sirh3e**
Refactored while loop.
Use standard function

### CODE REVIEW

**Comment by davidfowl** [comment]
Why? The older code was better.

**Comment by sirh3e** [comment]
Why was the old code better in which sense?
There is a standard function for this behavior.

**Comment by davidfowl** [comment]
Oh my bad, I thought the old code used TryDeque, this looks good 😄

**Comment by sirh3e** [comment]
No worries

**Review by jkotalik — APPROVED** [review]

**Pull request merged**
