### PR TITLE
DotNetWatcher: don't wait for file changes to restart when the process exits

### PR DESCRIPTION
**Pull request by tmds**
When not using `--watch` an app will restart immediately when it terminates.
This makes `--watch` also restart apps that terminate.

cc @jkotalik

### CODE REVIEW

**Comment by davidfowl** [comment]
It has to wait or you risk getting into a quick restart cycle when the app is in a broken state.

**Comment by tmds** [comment]
The app migrates a database at startup. It's expected to fail until the database container is running.
Without `--watch` the app restarts until the database was migrated. With `--watch` it fails on the first attempt and then waits until a file changes.
I think this difference is not expected.

The containers are also configured to continue restarting.

**Comment by davidfowl** [comment]
That difference by design.

**Comment by davidfowl** [comment]
Sorry is this just about containers?

**Comment by tmds** [comment]
It's about .NET applications.
`tye` restarts them when the exit. `tye --watch` does not. It's an unexpected difference.

containers are always restarted.

When the .NET apps fails to start because missing dependent services are not yet up, with `tye` it restarts until they are, with `tye --watch` it sits and waits for the user to make a move.

**Comment by davidfowl** [comment]
That's by design. The .NET applications wait for a change until they restart to avoid the restart loop. That's how watch tools work. As an example, if I change the port and there's a binding conflict, I want to wait for the next change to potentially fix that before I re-run again.

**Comment by tmds** [comment]
In this case, it fails to start because a dependent service is not yet up.

The not restarting is unexpected.

Maybe it can restart with a backoff timer?

**Comment by davidfowl** [comment]
Maybe its time to bite the bullet and add dependencies.

cc @glennc

**Comment by tmds** [comment]
> Maybe its time to bite the bullet and add dependencies.

Is this going to happen?

fwiw, I agree with what you said in https://github.com/dotnet/tye/issues/947#issuecomment-786190875:

> The reason we didn't do dependencies and startup order is because we didn't think it would be replicated in the production environments so giving people that false sense that it works locally is bad.

**Comment by aladd04** [comment]
Dug a bit to find this but I'm glad we found something out there about this behavior. My team is running into this issue, intermittently, too. Are there any updates for this feature?

For localdev we have a redis instance that needs to be up and ready before our APIs can bootstrap. `tye run` works perfect every time, restarting the API until it's ready. But `tye run --watch` will wait for a file change if it initially fails because redis isn't ready.

Our current workaround is to have two different tye yamls, one for `tye run` and one for `tye run --watch`.  The `tye run --watch` variant marks redis as an external dependency instead of an image. Downside is we have to go outside of tye and manually start that redis container first. Then manually shut it down if we want to run the other command.

**Comment by tmds** [comment]
> Dug a bit to find this but I'm glad we found something out there about this behavior. My team is running into this issue, intermittently, too. Are there any updates for this feature?

This PR fixes the issue by also restarting the app when using `--watch`.

It has not been merged because https://github.com/dotnet/tye/issues/947 offers a different solution. I don't think it is actively being worked on.

**Comment by davidfowl** [comment]
Closing this

**Pull request closed without merging**
