### PR TITLE
Fix ConfigApplicationParser to support network deserialization

### PR DESCRIPTION
**Pull request by alexfdezsauco**
Add support to deserialize network key at HandleConfigApplication method of ConfigApplicationParser

### CODE REVIEW

**Comment by davidfowl** [comment]
Oops!

**Comment by davidfowl** [comment]
You may want to add a test.

**Comment by alexfdezsauco** [comment]
Yes, I will

**Comment by alexfdezsauco** [comment]
Done

**Comment by davidfowl** [comment]
Thanks!

**Pull request merged**
